---
- name: install nginx
  hosts: host1
  tasks: 
    - name: install epel-release repo
      yum:
        name: epel-release
        state: latest

    - name: install nginx 
      yum: 
        name: nginx
        state: latest

    - name: start nginx
      systemd: 
        name: nginx
        state: started
        enabled: yes 

