---
- name: install nginx
  hosts: 10.108.0.2
  tasks: 
    - name: add epel-release repo
      yum:
        name: epel-release
        state: latest

    - name: install nginx 
      yum: 
        name: nginx
        state: latest

    - name: start nginx
      service: 
        name: nginx
        state: started

    - name: create index.html
      file: 
        path: /root/git-repos/ansible_playbooks/index.html
        state: touch
    - name: insert line to index.html
      blockinfile: 
        path: /root/git-repos/ansible_playbooks/index.html
        block: |
          <!DOCTYPE html>
          <html>
          <head>
          <title>My Website</title>
          </head>
          <body>

          <h1>Welcome to my page!</h1>
          <p>This my awesome website.</p>
          <img src="https://www.pexels.com/photo/3183197/download/?search_query=technology&tracking_id=27mp317lftr" alt="Italian Trulli">

          </body>
          </html>


     