---
- name: update packages, install packages, create and insert line in a file 
  hosts: managed_hosts
  tasks:
    - name: updating "yum" packages
      yum: 
        name: '*'
        state: latest  

    - name: install vim tree wget curl
      yum:
        name:
          - vim
          - tree
          - wget
          - curl
        state: latest
    - name: create an empty file
      file: 
        path: /tmp/file1_ansible
        state: touch
    - name: insert line to a file
      blockinfile: 
        path: /tmp/file1_ansible
        block: |
          This is line one
          This is line two




